/* eslint-disable no-unused-vars */
export enum ENUM_USER_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANUFACTURER = 'MANUFACTURER',
  IMPORTER = 'IMPORTER',
  WHOLESALER = 'WHOLESALER',
  DEALER = 'DEALER',
  RESELLER = 'RESELLER',
  STAFF = 'STAFF',
}
